spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbprod
    username: sa
    password: sa
  jpa:
    defer-datasource-initialization: true
cartMicroservice:
  url: localhost
  port: 8085
retry:
  maxAttempts: 2
  maxDelay: 100
server:
  port: 8084